/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  Sidebar: [
    'intro',
    'installation',
    'quick-start',
    {
      type: 'category',
      label: 'Concepts',
      items: 
      [
        'concepts/intro',
        'concepts/data-model',
        'concepts/entity-db-mapping',
        'concepts/zero-trust-programming',
        'concepts/declarative-dataflow',
        'concepts/resolvers',
      ],
    },
    {
      type: 'category',
      label: 'Language Reference',
      items: 
      [
        'language/overview',
        'language/component',
        {
          type: 'category',
          label: 'Data model',
          items: 
          [
            'language/data-model/entity',
            'language/data-model/relationship',
            'language/data-model/attribute',
            'language/data-model/record',
          ],
        },
        {
          type: 'category',
          label: 'Business Logic',
          items: 
          [
            'language/business-logic/event',
            'language/business-logic/dataflow',
            'language/business-logic/dataflow-patterns',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Blog Example',
      items: 
      [
        'blog-example/intro',
        'blog-example/data-model',
        'blog-example/build',
        'blog-example/relationships',
        {
          type: 'category',
          label: 'Business Logic',
          items: 
          [
            'blog-example/business-logic/create-post',
            'blog-example/business-logic/update-post',
            'blog-example/business-logic/delete-post',
            'blog-example/business-logic/add-authors',
            'blog-example/business-logic/comments',
          ],
        },
        'blog-example/next-steps',
        'blog-example/source-code',
      ],
    },
  ],
};

module.exports = sidebars;
