/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  Sidebar: [
    'intro',
    'installation',
    'quick-start',
    'tutorial',
    "rbac",
    {
      type: 'category',
      label: 'Concepts',
      items:
        [
          'concepts/intro',
          'concepts/data-model',
          'concepts/entity-db-mapping',
          'concepts/zero-trust-programming',
          'concepts/declarative-dataflow',
          'concepts/resolvers',
          'concepts/interceptors',
          'concepts/schema-migration'
        ],
    },
    {
      type: 'category',
      label: 'Language Reference',
      items:
        [
          'language/overview',
          'language/component',
          {
            type: 'category',
            label: 'Data model',
            items:
              [
                'language/data-model/record',
                'language/data-model/entity',
                'language/data-model/relationship',
                'language/data-model/attribute',
              ],
          },
          {
            type: 'category',
            label: 'Business Logic',
            items:
              [
                'language/business-logic/event',
                'language/business-logic/dataflow',
                'language/business-logic/dataflow-patterns',
              ],
          },
          {
            type: 'category',
            label: 'Kernel',
            items:
              [
                'language/kernel/intro',
                'language/kernel/lang',
                'language/kernel/identity',
                'language/kernel/rbac',
              ]
          },
        'language/config',
        ],
    },
    {
      type: "category",
      label: "Design Studio",
      items: [
        {
          type: 'category',
          label: "Reference",
          items: [{
            type: 'category',
            label: 'Dashboard',
            items:
              [
                'dashboard/intro',
                'dashboard/creating-a-model',
                'dashboard/importing-a-model'
              ],
          },
          {
            type: 'category',
            label: 'Data Model',
            items:
              [
                // 'data-model/intro',
                {
                  type: 'category',
                  label: "Components",
                  items: ['data-model/components/create-component', 'data-model/components/delete-component']
                },
                {
                  type: 'category',
                  label: "Entities",
                  items: ['data-model/entities/create-entity', 'data-model/entities/delete-entity', 'data-model/entities/add-attribute', 'data-model/entities/delete-attribute']
                },
                {
                  type: 'category',
                  label: "Records",
                  items: ['data-model/records/create-record', 'data-model/records/delete-record', 'data-model/records/add-attribute', 'data-model/records/delete-attribute']
                },
                {
                  type: 'category',
                  label: "Relationships",
                  items: ['data-model/relationships/create-relationship', 'data-model/relationships/delete-relationship', 'data-model/relationships/add-attribute', 'data-model/relationships/delete-attribute']
                }

              ],
          },
          {
            type: "category",
            label: "Dataflow",
            items: [
              "dataflow/navigate-to-dataflow-page",
              {
                type: "category",
                label: "Events",
                items: [
                  "dataflow/events/create-event",
                  "dataflow/events/delete-event",
                  "dataflow/events/add-attribute",
                  "dataflow/events/delete-attribute"
                ]
              },
              {
                type: "category",
                label: "Dataflows",
                items: [
                  {
                    type: "category",
                    label: "Adding Dataflow Pattern",
                    items: [
                      "dataflow/dataflows/adding-dataflow-pattern/create-pattern",
                      "dataflow/dataflows/adding-dataflow-pattern/update-pattern",
                      "dataflow/dataflows/adding-dataflow-pattern/query-pattern",
                      "dataflow/dataflows/adding-dataflow-pattern/delete-pattern",
                      "dataflow/dataflows/adding-dataflow-pattern/loop-pattern",
                      "dataflow/dataflows/adding-dataflow-pattern/match-pattern",
                      "dataflow/dataflows/adding-dataflow-pattern/event-pattern",
                      "dataflow/dataflows/adding-dataflow-pattern/reference-pattern",
                      "dataflow/dataflows/adding-dataflow-pattern/eval-pattern"
                    ]
                  },
                  "dataflow/dataflows/delete-dataflow-pattern"
                ]
              }
            ]
          },
          {
            type: "category",
            label: "RBAC",
            items: [
              "rbac/navigate-to-security",
              "rbac/component-rbac",
              "rbac/entity-rbac",
            ]
          }]
        },
      ]
    }

  ],
};

module.exports = sidebars;
